In [17]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [19]:
df = pd.read_csv("../dataset/olympics_athletes_dataset.csv")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '../dataset/olympics_athletes_dataset.csv'

In [ ]:
df.tail()

,athlete_id,athlete_name,gender,age,date_of_birth,nationality,country_name,sport,event,games_type,...,bronze_medals,country_total_gold,country_total_medals,country_first_participation,country_best_rank,is_record_holder,coach_name,height_cm,weight_kg,notes
8495,ATH-08496,Dorothy Meyer,Female,29,1995-10-12,KEN,Kenya,Ice Hockey,Women's Ice Hockey,Winter,...,2,38,109,1956,20,No,Renato Canova,187.9,77.4,Disqualified (false start)
8496,ATH-08497,Romain Ito,Male,18,2006-04-16,DPR,North Korea,Fencing,Foil Team M,Summer,...,3,16,54,1964,35,No,Vladimir Alekna,191.9,64.9,First from country
8497,ATH-08498,Magdalena Garcia,Female,36,1988-10-28,AUS,Australia,Short Track Speed Skating,1500m W,Winter,...,1,170,554,1896,4,No,Andrei Chemerkin,159.6,62.2,Comeback after injury
8498,ATH-08499,Leyla Kwon,Female,29,1995-02-04,BEL,Belgium,Shooting,10m Air Pistol M,Summer,...,2,43,158,1900,20,No,Sandor Szabo,184.9,75.9,Personal Best
8499,ATH-08500,Tirunesh Bekele,Female,37,1987-02-26,AUS,Australia,Swimming,200m Freestyle,Summer,...,1,170,554,1896,4,No,Bao Chünlai,188.0,56.8,Olympic Debut

In [ ]:
df.isnull().sum()

athlete_id                     0
athlete_name                   0
gender                         0
age                            0
date_of_birth                  0
nationality                    0
country_name                   0
sport                          0
event                          0
games_type                     0
year                           0
host_city                      0
team_or_individual             0
medal                          0
result_value                   0
result_unit                    0
total_olympics_attended        0
total_medals_won               0
gold_medals                    0
silver_medals                  0
bronze_medals                  0
country_total_gold             0
country_total_medals           0
country_first_participation    0
country_best_rank              0
is_record_holder               0
coach_name                     0
height_cm                      0
weight_kg                      0
notes                          0
dtype: int64

In [ ]:
df.describe()

,age,year,result_value,total_olympics_attended,total_medals_won,gold_medals,silver_medals,bronze_medals,country_total_gold,country_total_medals,country_first_participation,country_best_rank,height_cm,weight_kg
count,8500.000000,8500.000000,8500.000000,8500.00000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000
mean,28.531176,1967.250824,747.450624,2.98800,4.133647,2.037647,1.028941,1.067059,115.538353,341.887882,1919.541412,19.995529,178.873812,77.158753
std,8.074316,45.062096,1906.176179,1.42072,2.562461,2.042781,1.419565,1.459811,176.862799,456.193805,30.748547,17.602927,11.375077,16.528412
min,15.000000,1896.000000,0.011000,1.00000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,1896.000000,1.000000,145.000000,40.100000
25%,22.000000,1920.000000,10.359250,2.00000,2.000000,0.000000,0.000000,0.000000,19.000000,60.000000,1896.000000,4.000000,170.300000,65.100000
50%,28.000000,1984.000000,129.507500,3.00000,4.000000,1.000000,1.000000,1.000000,54.000000,196.000000,1900.000000,15.000000,178.700000,75.300000
75%,36.000000,2008.000000,345.382750,4.00000,6.000000,3.000000,1.000000,2.000000,170.000000,497.000000,1948.000000,33.000000,187.300000,87.300000
max,42.000000,2024.000000,14979.675000,5.00000,9.000000,8.000000,8.000000,8.000000,1061.000000,2638.000000,2008.000000,62.000000,215.000000,149.700000

In [ ]:
df.nunique()

athlete_id                     8500
athlete_name                   7478
gender                            2
age                              28
date_of_birth                  5590
nationality                      62
country_name                     61
sport                            33
event                           253
games_type                        2
year                             39
host_city                        31
team_or_individual                2
medal                             4
result_value                   8194
result_unit                       8
total_olympics_attended           5
total_medals_won                 10
gold_medals                       9
silver_medals                     9
bronze_medals                     9
country_total_gold               50
country_total_medals             58
country_first_participation      16
country_best_rank                32
is_record_holder                  3
coach_name                       28
height_cm                       604
weight_kg                       866
notes                            17
dtype: int64

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8500 entries, 0 to 8499
Data columns (total 30 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   athlete_id                   8500 non-null   str
 1   athlete_name                 8500 non-null   str
 2   gender                       8500 non-null   str
 3   age                          8500 non-null   int64
 4   date_of_birth                8500 non-null   str
 5   nationality                  8500 non-null   str
 6   country_name                 8500 non-null   str
 7   sport                        8500 non-null   str
 8   event                        8500 non-null   str
 9   games_type                   8500 non-null   str
 10  year                         8500 non-null   int64
 11  host_city                    8500 non-null   str
 12  team_or_individual           8500 non-null   str
 13  medal                        8500 non-null   str
 14  result_value                 8500 non-null   float64
 15  result_unit                  8500 non-null   str
 16  total_olympics_attended      8500 non-null   int64
 17  total_medals_won             8500 non-null   int64
 18  gold_medals                  8500 non-null   int64
 19  silver_medals                8500 non-null   int64
 20  bronze_medals                8500 non-null   int64
 21  country_total_gold           8500 non-null   int64
 22  country_total_medals         8500 non-null   int64
 23  country_first_participation  8500 non-null   int64
 24  country_best_rank            8500 non-null   int64
 25  is_record_holder             8500 non-null   str
 26  coach_name                   8500 non-null   str
 27  height_cm                    8500 non-null   float64
 28  weight_kg                    8500 non-null   float64
 29  notes                        8500 non-null   str
dtypes: float64(3), int64(11), str(16)
memory usage: 1.9 MB

In [ ]:
df.drop_duplicates(inplace= True)

totals = df.groupby('gender')['country_total_medals'].sum().reset_index()
print(totals)

   gender  country_total_medals
0  Female               1442992
1    Male               1463055

In [ ]:
sns.barplot(data = totals , x = 'gender' , y = 'gold_medals' , palette= 'viridis')

NameError: name 'sns' is not defined